### ISSUE TITLE
iOS build error: STKAudioPlayer.h not found

### ISSUE THREAD

**Issue by PocketHack** [tlenclos/react-native-audio-streaming#10]
I keep getting "STKAudioPlayer.h not found" on line 5 of ReactNativeAudioStreaming.h when trying to build the Example project for iOS.

I cloned this repo, ran `npm install` in the Example folder, opened `ios/Example.xcodeproj` and tried to build in XCode. Got the aforementioned error.

I tried cloning it again, running `npm install` followed by `react-native link react-native-audio-streaming` (it told me the library was already linked for both platforms). Opening the XCode project and trying to build produced the same error.

Should that work? That isn't working for me. Is it working for you?

**Comment by tlenclos** [comment]
The external library StreamingKit is managed with cocoapod and I haven't found a proper way to download it automatically. Please see the manual installation for iOS https://github.com/tlenclos/react-native-audio-streaming#ios, this should world.

**Comment by PocketHack** [comment]
I'm building the Example folder from this repo, which already has the right version of StreamingKit in it. The problem seems to be that $(PODS_ROOT) is not in the Header Search Paths for ReactNativeAudioStreaming.xcodeproj.
