### ISSUE TITLE
 undefined is not an object (evaluating '_react3.default.PropTypes.string')

### ISSUE THREAD

**Issue by kardoqadir** [tlenclos/react-native-audio-streaming#130]
When I run on the simulator it shows this error. 
I have installed via 
`"react-native-audio-streaming": "git+https://github.com/tlenclos/react-native-audio-streaming.git",`
I installed  prop-types.

**Comment by kardoqadir** [comment]
Fixed by cleaning build!

**Comment by rmilejcz** [comment]
`Fixed by cleaning build!`

What does this mean? I cleared my watchman cache, yarn cache, deleted node_modules, reinstalled still getting this error.
