### ISSUE TITLE
Unknown named module 'react' while running Example.

### ISSUE THREAD

**Issue by maotora** [tlenclos/react-native-audio-streaming#133]
Hi.

When I run example after I have installed everything with either npm or yarn then run

    npm run start

then 

    react-native run-android

I get that above error. "Unknown named module 'react'" on my emulator.

![screenshot_1515925131](https://user-images.githubusercontent.com/5174884/34914944-ed960476-f92d-11e7-839e-f4265cb94a65.png)

**Comment by vishu-daffodil** [comment]
Hi I am facing same issue. +1

**Comment by ajmalbinansari** [comment]
+1

**Comment by haithem-rihane** [comment]
+1

**Comment by maotora** [comment]
> react-native-audio-streaming is not maintained anymore. The main purpose was to play shoutcast streams with meta data and display a notification while playing.
> 
> Please see other projects like
> 
>     jsierles/react-native-audio to play local audio and record
>     zmxv/react-native-sound to play local audio with more controls
> 

I guess that explains it!
