### ISSUE TITLE
Notification not show on Android Oreo

### ISSUE THREAD

**Issue by dashracer** [tlenclos/react-native-audio-streaming#138]
Hi @tlenclos ,

Is this library not supporting latest android?
The notification shown on android version < Oreo. The audio still played on the background

**Comment by dashracer** [comment]
@tlenclos I've created a PR for this one

https://github.com/tlenclos/react-native-audio-streaming/pull/139

**Comment by tlenclos** [comment]
Should be fix on master. Thanks !
