### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by EstebanFuentealba** [tlenclos/react-native-audio-streaming#2]
Hello, in README.md  change

> Add `new ReactNativeAudioStreamingPackage()` to the list returned by the `getPackages()` method

by

> Add `new ReactNativeAudioStreamingPackage(MainActivity.class)` to the list returned by the `getPackages()` method

**Comment by tlenclos** [comment]
Thanks, fixed with https://github.com/tlenclos/react-native-audio-streaming/commit/de018c65204e2df538cfbd88f80cd4ff1789f25f.
