### ISSUE TITLE
Can we make notification on android and media center control on iOS optional ?

### ISSUE THREAD

**Issue by madhu314** [tlenclos/react-native-audio-streaming#27]
Was wondering if the play method can take extra parameter to control notification on android and media center on ios ?

currently the default behavior is to always show notification and there is no way to override it ?

Are there any plans for such enhancements for this library ? I really like this library and hope to see this enhancement of optional notifications/media center control. If you agree, I can work on a PR

**Comment by tlenclos** [comment]
You are right this should be optional, you can work on it if you want. 😃

**Comment by madhu314** [comment]
coool, I will give it a go.

**Comment by madhu314** [comment]
I have submitted a [PR](https://github.com/tlenclos/react-native-audio-streaming/pull/29) , please have a look

**Comment by tlenclos** [comment]
Fixed with release https://github.com/tlenclos/react-native-audio-streaming/releases/tag/v2.2.0, thanks !
