### ISSUE TITLE
libaac does not work in android Marshmallow & above

### ISSUE THREAD

**Issue by madhu314** [tlenclos/react-native-audio-streaming#30]
The library is running into [issue-76](https://github.com/vbartacek/aacdecoder-android/issues/76) mentioned in the libaac repo 

We need to update native so files and aac jar as mentioned in this [comment](https://github.com/vbartacek/aacdecoder-android/issues/76#issuecomment-209461745)

I have tested these changes and they work. I can submit a PR with the changes

**Comment by tlenclos** [comment]
Weird, it worked well for me, feel free to make a pull request.

I would love to replace aac with ExoPlayer though (see https://github.com/tlenclos/react-native-audio-streaming/issues/12).

**Comment by madhu314** [comment]
I have seen[#12](https://github.com/tlenclos/react-native-audio-streaming/issues/12), I agree, having ExoPlayer is the best approach going forward.

In the mean time I will send out a PR for newer libs of aac

**Comment by tlenclos** [comment]
Fixed with release https://github.com/tlenclos/react-native-audio-streaming/releases/tag/v2.2.0
