### ISSUE TITLE
hi! I used Redux,  I do not know how to introduce this

### ISSUE THREAD

**Issue by jlala** [tlenclos/react-native-audio-streaming#38]
hi! I used Redux,  I do not know how to introduce this

error：
Cannot read property 'play' of undefined
Caught an exception! TypeError: Cannot read property 'getStatus' of undefined

**Comment by sunyingming** [comment]
i have the same problem!

**Comment by tlenclos** [comment]
It seems that you are trying to use the module but the module is not linked or installed, please see installation instruction https://github.com/tlenclos/react-native-audio-streaming/blob/master/README.md#mostly-automatic-installation.
