### ISSUE TITLE
Stop working when app in background.

### ISSUE THREAD

**Issue by XavierColombel** [tlenclos/react-native-audio-streaming#39]
Is there a way to get it working when app is in background?

**Comment by tlenclos** [comment]
It should always work in background, do you have any error logs ?

**Comment by XavierColombel** [comment]
On simulator it works. On device, sound cuts when app is in background. I've tested on iOS : device (v9.3.5) and simulator (v10). I use RN 0.37.

**Comment by XavierColombel** [comment]
Here is a sample app if you wanna test : [https://github.com/XavierColombel/react-native-radio](url)

**Comment by tlenclos** [comment]
I think this is because you don't have the background mode enable on the Info.plist file.
See the example project https://github.com/tlenclos/react-native-audio-streaming/blob/master/Example/ios/Example/Info.plist#L53.

I will add this to the README.

**Comment by XavierColombel** [comment]
Perfect! Thank you.
