### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by brettpappas** [tlenclos/react-native-audio-streaming#4]
I am trying to install this but when I am in Xcode -> Build Phases I can't find libStreamingKit.a.

I followed the instructions for "Mostly Automatic" install. Can you explain what you mean by "add Pods.xcodeproj"? Am I supposed to just make a folder called Pods.xcodeproj?

**Comment by brettpappas** [comment]
I went through the manual install process on iOS and was able to get it working. I may submit a PR to update the directions since Pods.xcodeproj exists under the Pods folder not the ios folder.

**Comment by tlenclos** [comment]
Yes I'm sorry this is not really the best install process. I wanted to keep the pod dependency to avoid versionning it but I didn't find a nice way to do this, if you have any idea I'll take it !

**Comment by magicspon** [comment]
I'm unable to successfully build this for android.  I've followed the steps in the read.me to the letter.  Getting the following error.

```
/Users/stockley/websites/straightline/mobile/Straightline/android/app/src/main/java/com/straightline/MainApplication.java:27: error: cannot find symbol
          new ReactNativeAudioStreamingPackage(MainActivity.class)
              ^
  symbol: class ReactNativeAudioStreamingPackage
1 error
:app:compileDebugJavaWithJavac FAILED
```

**Comment by tlenclos** [comment]
@magicspon Did you also add the line `import com.reactlibrary.ReactNativeAudioStreamingPackage;` at the top of `MainApplication.java` ?

**Comment by magicspon** [comment]
@tlenclos I shall check and let you know shortly... thanks
