### ISSUE TITLE
Not able to install.....

### ISSUE THREAD

**Issue by Vjsharma** [tlenclos/react-native-audio-streaming#43]
Hi All,

I am getting bellow error while installing in my app....

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/7.1.0/bin/node" "/usr/local/bin/npm" "install" "react-native-audio-streaming" "--save"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9

npm ERR! shasum check failed for /var/folders/rs/30mhv4tn0gz3r05ls8h3bghr0000gn/T/npm-65450-120bf1d9/registry.npmjs.org/react-native-audio-streaming/-/react-native-audio-streaming-2.2.0.tgz
npm ERR! Expected: b02552893480c83281a19bbf2203927ec642c9f4
npm ERR! Actual:   ea7da3714c97383eb2d295f66a237f7bd386a967
npm ERR! From:     https://registry.npmjs.org/react-native-audio-streaming/-/react-native-audio-streaming-2.2.0.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:

**Comment by tlenclos** [comment]
This seems like a connectivity issue, I keep this issue open a little while just in case others have the same problem.
