### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by RocKhalil** [tlenclos/react-native-audio-streaming#46]
While using the `Automatic Installation` i'm getting an error while building my project:
```
Lexical or Preprocessor Issue
'/...../StreamingKit-prefix.pch' file not found
```

Any idea ?

**Comment by malachi358** [comment]
Im getting this error:

* What went wrong:
A problem occurred configuring project ':app'.
> Cannot evaluate module react-native-audio-streaming : Configuration with name 'default' not found.
 when i try  react-native run-android, does anyone have this issue?
thanks
