### ISSUE TITLE
exoplayer branch

### ISSUE THREAD

**Issue by petar-dambovaliev** [tlenclos/react-native-audio-streaming#52]
When i switch on the exo player branch stuff gets broken.

node_modules\react-native-audio-streaming\android\src\audioStreaming\Signal.java:211: error: cannot find symbol
      DataSource.Factory dataSourceFactory = new AudioStreamingD
(this.getApplication(), getDefaultUserAgent(), bandwidthMeter);
                                                 ^
symbol:   class AudioStreamingDataSourceFactory
location: class Signal
error
react-native-audio-streaming:compileReleaseJavaWithJavac FAILED

I need to stream m4a so i need to make this branch working.
Any ideas?

**Comment by lgan1989** [comment]
you can change `AudioStreamingDataSourceFactory ` to `DefaultDataSourceFactory`, see if it works.

**Comment by PetarDambovaliev** [comment]
@lgan1989 i already gave up react native because it's super buggy.
I started learning native development via java, it's pretty easy.

**Comment by pewh** [comment]
Hei @lgan1989, I've try to follow your instruction, and when build I get this error:
```
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexIndexOverflowException: Cannot merge new index66830 into a non-jumbo instruction!

```
