### ISSUE TITLE
Cannot read property 'play' of undefined

### ISSUE THREAD

**Issue by iamkyleee** [tlenclos/react-native-audio-streaming#64]
Couldn't get either the player nor the regular api to work
![image](https://cloud.githubusercontent.com/assets/7822506/22396285/b72118a6-e509-11e6-8d46-832d7633389e.png)

![image](https://cloud.githubusercontent.com/assets/7822506/22396267/8bbf7e78-e509-11e6-9b53-f14333690783.png)

**Comment by fakewaffle** [comment]
What was the issue?

**Comment by iamkyleee** [comment]
it does not work well with exponent. Also, I used the manual method and linked the libraries through xcode and worked.

**Comment by fakewaffle** [comment]
I'm having the same problem after following the directions. :(

**Comment by iamkyleee** [comment]
![image](https://cloud.githubusercontent.com/assets/7822506/22614809/ae3efbb2-ea3c-11e6-9770-8f498e1267ff.png)

This is what my Libraries looked like.

**Comment by anglol** [comment]
Something new here ? Same problem :(

**Comment by browncj** [comment]
Having the same issue, except it's telling me "cannot read property 'string' of undefined"

**Comment by 1k2k** [comment]
#127 @browncj  The problem is version of PropTypes used by this repo. This repo is using PropTypes from React, but PropTypes are moved to prop-types npm package. You can see it by going to index.js of repo and you will find this:
`Player.propTypes = { url: React.PropTypes.string.isRequired };`
