### ISSUE TITLE
'React/RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by LeonHwa** [tlenclos/react-native-audio-streaming#81]
When I follow the step 3,The Xcode show me the error.

**Comment by catalinmiron** [comment]
I have the same problem, how can I fix it?

**Comment by gwitteveen** [comment]
I had similar issues, but with a different module. Following the steps in the accepted answer in the link below fixed it for me.

https://stackoverflow.com/questions/41477241/react-native-xcode-upgrade-and-now-rctconvert-h-not-found

**Comment by savioseb** [comment]
I had the same problem - the `pod install` approach doesn't work for me. the 2nd approach `react-native link react-native-audio-streaming` works for me.
